version: '3.7'

services:
  db:
    image: postgres:11.9
    container_name: database
    environment:
      - "POSTGRES_USER=username"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=broker"
    networks:
      - integration-test
    ports:
      - "5432:5432"
    healthcheck:
      test: [CMD-SHELL, 'pg_isready -h postgres -p 5432 -U user -d password']
      interval: 1s
      timeout: 1s
      retries: 10

networks:
  integration-test:
    driver: bridge
    name: integration-test