version: '3.7'

services:
  db:
    image: postgres:13.1-alpine
    container_name: database
    environment:
      # Create db
      POSTGRES_DB: 'broker'
      POSTGRES_USER: 'username'
      POSTGRES_PASSWORD: 'password'
      TZ: UTC
    volumes:
      - vertx-stock-broker-data-local:/var/lib/postgresql/data
    ports:
      - "5432:5432"

#  pgadmin:
#    container_name: pgadmin4
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: root
#    ports:
#      - "5050:80"

# permanent storage of data.
# > docker volume rm postgres_vertx-stock-broker-data-local
volumes:
  vertx-stock-broker-data-local: